version: '0.1.0'

services:
  backend:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./tests/apps/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

