[tool.poetry]
name = "cnter"
version = "0.1.0"
description = ""
authors = ["sverdejot <samularoda@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.78.0"
neo4j = "^4.4.4"
python-dotenv = "^0.20.0"
neo4j-driver = "^4.4.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
